### ISSUE TITLE
Piped stream

### ISSUE THREAD

**Issue by simon-p-r** [gregberge/std-mocks#1]
Hi

I am trying to test a stream piping to stdout however when piping to stdout from a readable stream both stdout and stderr arrays are empty so I cannot test output to console.  Any help would be appreciated!

Thanks
Simon

**Comment by gregberge** [comment]
@simon-p-r sorry for the response time, have you solved your issue?

**Comment by simon-p-r** [comment]
I will re-open if I have a problem when I use module again
